apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ssmconfigs.ssm.aws.605.tv
spec:
  group: ssm.aws.605.tv
  names:
    kind: SsmConfig
    listKind: SsmConfigList
    plural: ssmconfigs
    singular: ssmconfig
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: SsmConfig is the Schema for the ssmconfigs API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: SsmConfigSpec defines the desired state of SsmConfig
              type: object
              properties:
                env:
                  description: Environment
                  type: string
                ssmKeys:
                  description: AWS SSM parameter key paths
                  type: array
                  items:
                    type: string
            status:
              description: SsmConfigStatus defines the observed state of SsmConfig
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
