kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-aws-operator
subjects:
  - kind: ServiceAccount
    name: k8s-aws-operator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-aws-operator
  apiGroup: rbac.authorization.k8s.io
