kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-aws-operator
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: k8s-aws-operator
roleRef:
  kind: Role
  name: k8s-aws-operator
  apiGroup: rbac.authorization.k8s.io
